name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24']
        elixir: ['1.13']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Project
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock'))}}
    - name: Install and compile dependencies
      run: mix do deps.get, deps.compile
    - name: Compile
      run: mix compile
    - name: Run tests and coverage
      run: mix coveralls
    - name: Extract Coverage Stats
      run: |
        COVERALLS_OUTPUT=$(mix coveralls)
        COVERAGE=$(echo $COVERALLS_OUTPUT | grep "\[TOTAL\]" | grep -Po "[0-9]+\.[0-9]*%")
        COVERAGE_COLOR=$(echo $COVERAGE | grep -Po "^[0-9]+")
        echo "COVERAGE=$(echo $COVERAGE | cut -c 1-6)" >> $GITHUB_ENV
        echo "COVERAGE_COLOR=$(echo $COVERAGE_COLOR | cut -c 1-6)" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.3.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: ex_banking_coverage.json
        label: Coverage
        namedLogo: coveralls.svg
        message: ${{ env.COVERAGE }}
        valColorRange: ${{ env.COVERAGE_COLOR }}
        maxColorRange: 100
        minColorRange: 50
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: cover
